//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace amsdemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblExpens
    {
        public int ExpenseId { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<int> Month { get; set; }
        public string CompanyCode { get; set; }
        public string CityCode { get; set; }
        public string ExpenseType { get; set; }
        public Nullable<int> PurchaseId { get; set; }
        public Nullable<int> PayrollId { get; set; }
        public Nullable<decimal> Amount { get; set; }
    
        public virtual tblPayroll tblPayroll { get; set; }
        public virtual tblPurchase tblPurchase { get; set; }
    }
}
