//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace amsdemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEmployeeDetail
    {
        public int EmployeeId { get; set; }
        public string EmployeeStatus { get; set; }
        public Nullable<System.DateTime> Dateofjoining { get; set; }
        public Nullable<System.DateTime> Dateofresignation { get; set; }
        public Nullable<System.DateTime> DateofTransfer { get; set; }
        public Nullable<System.DateTime> DateofPromotion { get; set; }
        public Nullable<System.DateTime> LastLeaveDate { get; set; }
    
        public virtual tblEmployee tblEmployee { get; set; }
    }
}
