//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace amsdemo.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tblOrganizationStructure
    {
        [Range(1000,9999)]
        public int CompanyCode { get; set; }
        [Required]
        [Range(100,500)]
        public int CityCode { get; set; }
        [Required]
        public string StorageLocation { get; set; }
        [Required]
        public string PurchaseOrganization { get; set; }
    }
}
