//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace amsdemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOrganizationStructure
    {
        public int CompanyCode { get; set; }
        public Nullable<int> CityCode { get; set; }
        public string StorageLocation { get; set; }
        public string PurchaseOrganization { get; set; }
    }
}
