//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace amsdemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPayroll
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblPayroll()
        {
            this.tblExpenses = new HashSet<tblExpens>();
        }
    
        public int PayrollId { get; set; }
        public string FortheMonth { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<int> CompanyCode { get; set; }
        public Nullable<int> CityCode { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public Nullable<decimal> BasicSalary { get; set; }
        public Nullable<decimal> GrossSalary { get; set; }
        public Nullable<decimal> Bonuses { get; set; }
        public Nullable<decimal> IncomeTax { get; set; }
        public Nullable<decimal> MedicalAllowance { get; set; }
        public Nullable<decimal> TotalDeduction { get; set; }
        public string NetSalary { get; set; }
    
        public virtual tblEmployee tblEmployee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblExpens> tblExpenses { get; set; }
    }
}
