//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace amsdemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPurchaseitem
    {
        public int Id { get; set; }
        public Nullable<int> PurchaseId { get; set; }
        public Nullable<int> ItemId { get; set; }
        public Nullable<int> NoofMissingStock { get; set; }
        public Nullable<int> NoofDamagedStock { get; set; }
    
        public virtual tblItem tblItem { get; set; }
        public virtual tblPurchase tblPurchase { get; set; }
    }
}
